models/Projects.php
<?php

namespace app\models;

use app\models\PurchaseConversionsArchive;

use Yii;

/**
 * This is the model class for table "projects".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property integer $active
 */
class Projects extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'title', 'active'], 'required'],
            [['user_id', 'active', 'to_delete'], 'integer'],
            [['title', 'domain', 'screenshot'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'title' => 'Title',
            'active' => 'Active',
        ];
    }
	
	
	

	 
	 

    
	
 
			 
 
	 
	 
	 
	 
	 
 
}

controllers/ProjectsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Projects;
use app\models\Orders;
use app\models\People;
use app\models\ProjectSettings;
use app\models\UserSettings;
use app\models\Store;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use dektrium\user\models\User;
use yii\db\Expression;
// use Datetime;
/**
 * ProjectsController implements the CRUD actions for Projects model.
 */
class ProjectsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionIndex()
    {
		
		$this->layout = "dark_layout";
		
		
        $dataProvider = new ActiveDataProvider([
            'query' => Projects::find(),
        ]);
		
		$model = new Projects();
		
        if ($model->load(Yii::$app->request->post())) {
			
			
			$admin_user_id = Yii::$app->user->getId();
			
			
			$model->user_id = $admin_user_id;
			$model->save(false);
				
				
            return $this->redirect(['index', 'id' => $model->id]);
        
		} else {
	        return $this->render('index', [
	            'dataProvider' => $dataProvider,
	        ]);
        }
		
		

 
    }

    /**
     * Displays a single Projects model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($project_id)
    {
		
		$this->layout = "dark_layout";
		
		
        return $this->render('view', [
            'model' => $this->findModel($project_id),
        ]);
    }
	
	
    public function actionOverview($project_id)
    {
        if ( Yii::$app->user->isGuest ){
            return $this->redirect('/user/login');
        }
        
        $session = Yii::$app->session;
        if ($session->has('last_login_user')) {
            $todayTo = date('yy-m-d H:i:s', $session['last_login_user']);
        } else {
            $session['last_login_user'] = time();
            $todayTo = date('yy-m-d H:i:s', $session['last_login_user']);
            $userModel = User::findOne(['id' => Yii::$app->user->id]);
            $userModel->updateAttributes(['last_login_at' => $session['last_login_user']]);
        }
              
		$cookies = Yii::$app->response->cookies;
					// add a new cookie to the response to be sent
					$cookies->add(new \yii\web\Cookie([
					    'name' => 'last_project_id',
					    'value' => $project_id,
					]));
					
                   $date = Yii::$app->request->get('date');
            
        
        //get minimal date from database for Datapicker
        $minDateForChart = Orders::getMinDateByProjectID($project_id);

        //get maximal date from database for Datapicker
        $maxDateForChart = Orders::getMaxDateProjectID($project_id);
                    
        //get all dates in format '04/20/2020 00:00:00'
        $todayFrom = date('yy-m-d 00:00:00');
        $yesterday = date('yy-m-d 24:00:00', strtotime( '-1 days' ));
        $past7days = date('yy-m-d 24:00:00', strtotime( '-7 days' ));
        $past14days = date('yy-m-d 24:00:00', strtotime( '-14 days' ));
        $past30days = date('yy-m-d 24:00:00', strtotime( '-30 days' ));

        // get data today Revenue, Orders and People
        $revenueOrdersToday = Orders::getDataByDatesRevenueAndOrders($project_id, $todayFrom, $todayTo);
        $peopleToday = People::getDataByDatesRevenueAndOrders($project_id, $todayFrom, $todayTo);

        //get data during 7 days
        $revenue7PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past7days, $yesterday), 'revenue');
        $orders7PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past7days, $yesterday), 'orders');
        $people7PastDays = People::getSumArrayByKey(People::getDataByDatesRevenueAndOrders($project_id, $past7days, $yesterday), 'people');

        //get data during 14 days
        $revenue14PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past14days, $yesterday), 'revenue');
        $orders14PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past14days, $yesterday), 'orders');
        $people14PastDays = People::getSumArrayByKey(People::getDataByDatesRevenueAndOrders($project_id, $past14days, $yesterday), 'people');
        
        //get data during 30 days
        $revenue30PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past30days, $yesterday), 'revenue');
        $orders30PastDays = Orders::getSumArrayByKey(Orders::getDataByDatesRevenueAndOrders($project_id, $past30days, $yesterday), 'orders');
        $people30PastDays = People::getSumArrayByKey(People::getDataByDatesRevenueAndOrders($project_id, $past30days, $yesterday), 'people');
                    
					//$revenue_array = Projects::revenue($project_id, $date);
					//$sevendays = $revenue_array['purchase_conversion_value_7'];
					
					//echo"$sevendays <br /><br />";
					
					//print_r($revenue_array);
					
					//die();
							
        return $this->render('overview', [
            'model'                 => $this->findModel($project_id),
            'minDate'               => date('yy-m-d', $minDateForChart),
            'maxDate'               => date('yy-m-d', $maxDateForChart),
            'revenueOrdersToday'    => $revenueOrdersToday,
            'peopleToday'           => $peopleToday,
            'revenue7PastDays'       => $revenue7PastDays,
            'orders7PastDays'        => $orders7PastDays,
            'revenue14PastDays'      => $revenue14PastDays,
            'orders14PastDays'       => $orders14PastDays,
            'revenue30PastDays'      => $revenue30PastDays,
            'orders30PastDays'       => $orders30PastDays,
            'people7PastDays'        => $people7PastDays,
            'people14PastDays'       => $people14PastDays,
            'people30PastDays'       => $people30PastDays
        ]);
    }

    public function actionUpdateChart()
	{
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();

            //check today date
            if($data['to'] == date('yy-m-d 24:00:00')) {
                $session = Yii::$app->session;
                if ($session->has('last_login_user')) {
                    $dateTo = date('yy-m-d H:i:s', $session['last_login_user']);
                }
            } else {
                $dateTo = $data['to'];
            }

            //get data about Revenue and Orders from DB 
            $dataChart = Orders::getDataByDatesRevenueAndOrders($data['project_id'], $data['from'], $dateTo);

            // create Array of Data for Chart
            $chartArray = array();
            array_push($chartArray, array('Date', 'Revenue', 'Orders'));
            if (!$dataChart) {
                array_push($chartArray, array('', 0, 0));
            } else {
                foreach($dataChart as $item) {
                    array_push($chartArray, array(date('m-d-yy',strtotime($item['ndate'])), doubleval($item['revenue']), doubleval($item['orders'])));
                }
            }

            return json_encode($chartArray);
        }
    }
	
	

    /**
     * Creates a new Projects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Projects();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }


	
	
    public function actionNew()
    {
        
		$admin_user_id = Yii::$app->user->getId();
		
		$usersettings = UserSettings::findOne(['user_id' => $admin_user_id]);
		
		$superadmin_id = $usersettings->superadmin_id;
		
		
		$user = User::findOne($admin_user_id);
		
		$model = new Projects();
		$model->user_id = $superadmin_id;
		$model->to_delete = 0;
		$model->title = "Untitled";
	
		
	 $email = $user->email;
	 
	 $email_array = explode('@',$email);
	 
	 $firstpart = $email_array[0];
	 
	 $email_fixed = str_replace('.','', $firstpart);
	 
	 $rand = rand(1,900);
	 
	 $username = $email_fixed.$rand;
	 
	 	
		
			$model->save(false);
			
			
		$ps = new ProjectSettings();
		$ps->project_id = $model->id;
		
		$ps->superadmin_id = $superadmin_id;
		$ps->username = $username;
		
		$ps->id = $model->id;
		
		$ps->save(false);
		
		$project_id = $ps->project_id;
		
		Store::initial_template(1, $project_id);
			
			
		return $this->redirect(['project-settings/onboarding', 'project_id' => $ps->project_id]);
        
    }
	
	
	
	
    /**
     * Updates an existing Projects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Projects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }



    public function actionRemove($id)
    {
        $model = $this->findModel($id);
		

views/projects/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'active')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projects/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Create Projects';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/projects/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

use app\models\Projects;
use app\models\ProjectSettings;
use app\models\UserSettings;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Projects';
$this->params['breadcrumbs'][] = $this->title;

$admin_user_id = Yii::$app->user->getId();

			
?>


<div style="max-width: 950px; margin: auto">
	
	<h1 class="page-title-h1" style="text-align: center">Projects</h1>


<div class="explainer" style="text-align: center">
Welcome back! Choose a project you want to work on.
</div>

<div class="panel panel-darkblue" id="variation-01" style="padding-left: 16px; padding-right: 16px; padding-bottom: 20px;">
			
			
			
			
			<div class="panel-body" style="width: 100%">
				                                    
													
													
								   					<div class="modal" id="create-project-menu">
								   					  <div class="modal-background"></div>
								   					  <div class="modal-content" style="background-color: #3a3b43; color: rgba(225,235,245,.95);">
								   					    <!-- Any other Bulma elements you want -->
						
								   						<div class="modal-content-padding" style="padding: 30px; text-align: center">
								   					
												<?php
													
												/*
												
												
													<?php
														
														$model = new Projects();
														
													?>
													
												    <?php $form = ActiveForm::begin(); ?>

												    <?= $form->field($model, 'title')->textInput(['maxlength' => true, 'placeholder' => 'My Cool Website Title']) ?>

												    <?= $form->field($model, 'domain')->textInput(['placeholder' => 'https://']) ?>

												    <div class="form-group">
												        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
												    </div>

												    <?php ActiveForm::end(); ?>
												*/
													
												?>
													
													
													
												
								   						</div>
						
								   					  </div>
								   					  <button class="modal-close is-large" aria-label="close"></button>
								   					</div>
													
													
													
										
										
						<div class="columns">
													
													
										            <?php
										            	
													$superadmin_id = UserSettings::superadmin_id();	
							
													$usersettings = UserSettings::findOne(['user_id' => $admin_user_id]);
							
													if ($usersettings->project_id && $usersettings->team_permissions == 3)
													{
														// means only have access to this one project, is just a team member, cant create new projects
								
														$projects = Projects::find()->where(['user_id' => $superadmin_id, 'to_delete' => 0, 'id' => $usersettings->project_id])->all();
								
							
													}
													else
													{
														$projects = Projects::find()->where(['user_id' => $superadmin_id, 'to_delete' => 0])->all();
														
														?>
														
														
														
																<div class="single-funnel-content column" style="height: 340px; border-radius: 0px; display: inline-block; border-radius: 12px; box-sizing: border-box; overflow: hidden; border: 6px dashed #4e4f52;" id="create-new-project">
																
																
														
											                
																
																
															  <div class="panel-body panel" style="padding: 20px; background-color: #27282a; height: 340px;">
         												   	
															
																						   
															   <div class="center" style='width: 80%;'>
														   
														   															   
																	   <div style="font-size: 80px; font-weight: normal; top: -5px; position: relative;">
																		   &#65291;
																	   </div>
															   
																	   <div style="font-size: 24px; font-weight: bold; color: #FFF; margin-bottom: 10px; top: -20px; position: relative;">NEW PROJECT</div>
														   
														 
															  
														<div style=' top: -20px; position: relative;'>Consider each project a different website or brand. Every project is connected to its own domain or subdomain.</div>
															   
															   														  
															   </div>
													   
													   
								   					
													
													
														   
		   	   
																</div> <!-- end panel-body panel -->
							
							
															</div> <!-- end single-funnel-content column -->
															
															
														<?php
							
													}
													
										            ?>
													
													
													
													
											
													
													
													
				                                    
											
													
													
																													
															
								<?php
									
							
								
								$x = 0;
								
								foreach ($projects as $project)
								{
									
										
									
									$project_domain = "";
									
									
									$projectsettings = ProjectSettings::find()->where(['project_id' => $project->id])->one();
									
									if ($projectsettings)
									{
										if ($projectsettings->domain)
										{
											$project_domain = $projectsettings->domain;
										}
										elseif ($projectsettings->username)
										{
											$project_domain = "";
										}
									}
									
									if ($projectsettings)
									{
										$project_title = $projectsettings->username;
									
									}
									else
									{
										$project_title = $project->title;
									}
									
									
									
									?>
									
									
									
										<div class="single-funnel-content column" style="min-height: 340px; border-radius: 0px; display: inline-block; border-radius: 12px; overflow: hidden;" id="project-<?= $project->id ?>">
																
																
										
											                    
																
																
									     <div class="panel-body panel" style="padding: 20px; background-color: #27282a; height: 100%; background-size: cover;
											 
											 
											background: linear-gradient(
											 		      rgba( 22, 22, 22, 0.5 ), rgba(22, 22, 22, 0.5)
											 		    ),

											 		    url('<?= $project->screenshot ?>') no-repeat center center">
         												   	
															
																		   <div>
																			   
															
															
															<?php
																
																
															if ($usersettings->team_permissions == 1)
															{
																?>
																
																<ul style='position: absolute; top: 10px; right: 20px; font-size: 32px;' class='ellipses-dropdown'>
																<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog" style="font-size: 45%; position: relative; left: 8px"></i></a>
																<ul class="dropdown-menu inner-dropdown-menu">
																	<li style='position: relative; left: -6px'><a href="<?= Url::to(['project-settings/onboarding', 'project_id' => $project->id])?>"><i class="fas fa-edit" style='font-size: 80%; position: relative; top: -1px'></i> Rename</a></li>
	
																	<li style='position: relative; left: -6px'><a href="<?= Url::to(['project-settings/update', 'project_id' => $project->id])?>"><i class="fas fa-cog" style='font-size: 80%; position: relative; top: -1px'></i> Settings</a></li>
								
					
																<li style='position: relative; left: -6px'><a href="<?= Url::to(['projects/remove', 'id' => $project->id ]) ?>" onclick="return confirm('Are you sure?');"><i class="fas fa-times"></i> Delete</a></li>
																</ul>
																</li>
																</ul>
																
																<?php
															}
															?>
															
															
																			   
																			
								<div class="center" style="width: 100%; padding: 20px; text-align: center;">
								
					
								
								
								
								
								
								
													             
	<span style="font-size: 32px; font-weight: bold; text-transform: uppercase"><?= $project_title ?></span>
																			   
											<br />
<span style="font-size: 13px; text-transform: uppercase; color: #ccc"><?= $project_domain ?></span>						
																		   
																		   
							<br /><br />
																											   
<button class='button is-primary' style='border: 0px; cursor: pointer;' id='select-<?= $project->id ?>'>
select project
</button>
																							  
																							  			   
																		   	</div>
																	   	  
																		 
																		  
																		  
																		  
																		  </div>
													   
																		   
													<script>
														$(function() {
														    $('.confirm1').click(function() {
														        return window.confirm("Are you sure?");
														    });
														});
													</script>	   
		   	   
										</div> <!-- end panel-body panel -->
							
							
									</div>
									
				
									
									
									<script>
										$("#select-<?= $project->id ?>").click(function () {
								
											window.location.href = '<?= Url::to(['funnels/index', 'project_id' => $project->id]) ?>';	
										});
									</script>
									
									
									<?php
									
									if ($x % 2 == 0)
									{
										?>
									</div>
									
									<div class="columns">
										<?php
									}
									$x++;
									
									
									
								}
									
									
								
								
								
								
								?> <!-- end single-funnel-content column -->
							
							
			
															
															
							</div> <!-- end columns-->
																	
				  
				  
				  
				      </div> <!-- end panel body -->
										
										
				</div> <!-- end panel dark blue-->
										
										<script>
											
											$( document ).ready(function() {
	
				
		
														
				
				
											$(".main-button").click(function () {
			
												console.log('in here');
											    $(this).addClass('is-loading');
											           setTimeout(function () {
											               $(this).removeClass('is-loading');
											           }, 2000);
				
											});
			
											$("#create-new-project").click(function () {
			
												//console.log('in here 2');
											    //$("#create-project-menu").addClass('is-active');
												
												window.location.href = '<?= Url::to(['projects/new']) ?>';	
												
			          
				
											});
			
			
											$(".modal-close").click(function () {
				
												$(".main-button").removeClass('is-loading');
											    $(".modal").removeClass('is-active');
			     
				 
											});
											
										});
										</script>
											
											
								
								<style>
									.nav-left {
										
									}
									
									.page-sidebar {
										display: none;
									}
									
									.page-content2 {
										width: 100% !important;
									}
									
									@media screen and  (min-width: 800px)
									{
										.column {
											max-width: 47% !important;
											margin: 2% !important;
										}	
										
									}
									
									tr, table, td {
										text-align: center !important;
									}
								
								
								
									.single-funnel-content:hover {
				
										 filter: brightness(110%) !important;
										cursor: pointer !important;
									}
									
									.left-bg {
										position: fixed; left: 0px; top: 0px; height: 100%; width: 0px; background-color: #3a3b43 !important; display: none;
									}
									
								</style>
								
								
								<style>
									.inner-dropdown-menu {
										z-index: 2147483647;
										left: -80px;
										top: 50px;
										width: 125px !important;
										min-width: 0px;
									}
			
									.inner-dropdown-menu:after {
									    position: absolute;
									    top: -7px;
									    right: 12px;
									    left: auto;
									    display: inline-block !important;
									    border-right: 7px solid transparent;
									    border-bottom: 7px solid #fff;
									    border-left: 7px solid transparent;
									    content: '';
									}	
								</style>
								
										
										
</div> <!-- end projects-->

views/projects/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Update Projects: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="projects-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/projects/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'title',
            'active',
        ],
    ]) ?>

</div>